remote_theme: "just-the-docs/just-the-docs"

color_scheme: "dark"

just_the_docs:
  show_on_navigation: true
  show_last_modified_date: true
  show_breadcrumbs: true
  collapse_level: 2
  aux_links:
    "GitHub Repository": https://github.com/dibe-sh/cleaner
    "Contact Support": mailto:contact@dibe.sh